CREATE TABLE IF NOT EXISTS Status (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS Extension (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS Type (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS User (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE NOT NULL,
    Password TEXT NOT NULL,
    Role TEXT DEFAULT 'user',
    CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Image (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT,
    Extension INTEGER,
    Type INTEGER,
    ReadyForTraining boolean,
    DateTime TEXT,
    Path TEXT,
    Status INTEGER,
    Text TEXT,
    FOREIGN KEY (Extension) REFERENCES Extension(ID),
    FOREIGN KEY (type) REFERENCES Type(ID),
    FOREIGN KEY (Status) REFERENCES Status(ID)
);

CREATE TABLE IF NOT EXISTS Object (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT,
    Status INTEGER,
    Detection REAL,
    x1 INTEGER,
    y1 INTEGER,
    x2 INTEGER,
    y2 INTEGER,
    FOREIGN KEY (Status) REFERENCES Status(ID)
);

CREATE TABLE IF NOT EXISTS ImageObjectLink (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Image INTEGER,
    Object INTEGER,
    FOREIGN KEY (Image) REFERENCES Image(ID),
    FOREIGN KEY (Object) REFERENCES Object(ID)
);

-- Optional: pre-fill Status values
INSERT OR IGNORE INTO Status (Title) VALUES ('Good'), ('Middle'), ('Faulty');
INSERT OR IGNORE INTO Type (Title) VALUES ('Object'), ('Text'), ('Money');
